# Generated by Django 5.2 on 2025-10-02 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiodataPeserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kewarganegaraan', models.CharField(max_length=50)),
                ('nomor_kk', models.CharField(max_length=20, unique=True)),
                ('nik', models.CharField(max_length=20, unique=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('anak_ke', models.IntegerField()),
                ('pendidikan_terakhir', models.CharField(max_length=50)),
                ('negara', models.CharField(max_length=50)),
                ('provinsi', models.CharField(max_length=50)),
                ('kabupaten', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('jalan', models.CharField(max_length=100)),
                ('kode_pos', models.CharField(max_length=10)),
                ('jurusan', models.CharField(max_length=100)),
                ('ukuran_seragam', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
