# Generated by Django 5.2.6 on 2025-10-04 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodatapeserta',
            name='jurusan',
            field=models.CharField(choices=[('Rekayasa Perangkat Lunak', 'Rekayasa Perangkat Lunak'), ('MultiMedia', 'MultiMedia'), ('Teknik Komputer Jaringan', 'Teknik Komputer Jaringan')], max_length=30),
        ),
        migrations.CreateModel(
            name='BerkasSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_profile', models.ImageField(upload_to='berkas_siswa/foto_profile/', verbose_name='Foto Profil')),
                ('surat_keterangan_lulus', models.ImageField(upload_to='berkas_siswa/surat_keterangan_lulus/', verbose_name='Surat Keterangan Lulus')),
                ('ijazah', models.ImageField(upload_to='berkas_siswa/ijazah/', verbose_name='Ijazah')),
                ('ktp_orang_tua_lk', models.ImageField(upload_to='berkas_siswa/ktp_ayah/', verbose_name='KTP Ayah')),
                ('ktp_orang_tua_pr', models.ImageField(upload_to='berkas_siswa/ktp_ibu/', verbose_name='KTP Ibu')),
                ('foto_kk', models.ImageField(upload_to='berkas_siswa/foto_kk/', verbose_name='Foto Kartu Keluarga (KK)')),
                ('foto_akte_kelahiran', models.ImageField(upload_to='berkas_siswa/foto_akte_kelahiran/', verbose_name='Foto Akte Kelahiran')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='berkas_siswa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Berkas Siswa',
                'verbose_name_plural': 'Data Berkas Siswa',
            },
        ),
    ]
