# Generated by Django 5.2.6 on 2025-10-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0002_alter_biodatapeserta_jurusan_berkassiswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodatapeserta',
            name='ukuran_seragam',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=5),
        ),
    ]
