# Generated by Django 5.2.6 on 2025-10-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0003_alter_biodatapeserta_ukuran_seragam'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatapeserta',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu Verifikasi'), ('lulus', 'Lulus'), ('tidak_lulus', 'Tidak Lulus')], default='menunggu', help_text='Status verifikasi pendaftaran peserta.', max_length=20),
        ),
    ]
